### ISSUE TITLE
Unexpected token

### ISSUE THREAD

**Issue by SloppierKitty7** [Brayzure/DiscordMusic#1]
module.js:561
    throw err;
    ^

SyntaxError: E:\mybot\audio\src\secret.json: Unexpected token / in JSON at position 126
    at Object.parse (native)
    at Object.Module._extensions..json (module.js:558:27)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (E:\mybot\audio\bot.js:8:11)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)

**Comment by Brayzure** [comment]
Hey thanks for pointing that out, I'll update it in the next few hours.

**Comment by SloppierKitty7** [comment]
So what was wrong with it?
